name: Install dependencies
description: Installs OS-specific dependencies for builds
runs:
  using: "composite"
  steps:  
    - name: Install ffmpeg & tauri deps (Ubuntu)
      if: matrix.platform == 'ubuntu-latest' || matrix.platform == 'macos-latest'
      shell: bash
      run: ./.github/scripts/setup-system.sh

    - name: Install vcpkg & ffmpeg (Windows)
      if: matrix.platform == 'windows-latest'
      shell: powershell
      run: |
        $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
        Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
        Invoke-WebRequest "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z" -OutFile ffmpeg-release-full-shared.7z
        7z x ffmpeg-release-full-shared.7z
        mkdir ffmpeg
        mv ffmpeg-*/* ffmpeg/
        Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
        Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"