name: Rust Clippy Check

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**/.rs'

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install Clippy
        run: rustup component add clippy
      - name: "Run Clippy"
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features